version: 2
registries:
  npm-registry-nexus-mgmt-oscato-com-repository-npm-release:
    type: npm-registry
    url: https://nexus.mgmt.oscato.com/repository/npm-release/
    token: "${{secrets.NPM_REGISTRY_NEXUS_MGMT_OSCATO_COM_REPOSITORY_NPM_RELEASE_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.17
  - dependency-name: react-i18next
    versions:
    - 11.8.5
    - 11.8.6
    - 11.8.7
    - 11.8.8
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: inferno
    versions:
    - 7.4.7
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@reduxjs/toolkit"
    versions:
    - 1.5.0
  - dependency-name: "@babel/plugin-transform-object-assign"
    versions:
    - 7.12.1
  - dependency-name: "@babel/polyfill"
    versions:
    - 7.12.1
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  registries:
  - npm-registry-nexus-mgmt-oscato-com-repository-npm-release
