name: Pull Request

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.19.3
        cache: 'npm'
    - name: Run Test Script
      env:
        CI: true
        BRANCH_STRATEGY: release
        MERCHANT_NAME: ${{ secrets.MERCHANT_NAME }}
        MERCHANT_TOKEN: ${{ secrets.MERCHANT_TOKEN }}
      run: |
        env
        npm ci
        npm test

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Payoneer's Github Actions"
        if: failure()
